#!/usr/bin/env zsh

PLUGIN_SHARE="/etc/profiles/per-user/$USER/share"
PLUGIN_DIR="$PLUGIN_SHARE/zsh/plugins"

source "$PLUGIN_SHARE/fzf-tab/fzf-tab.plugin.zsh"
source "$PLUGIN_DIR/zsh-autosuggestions/zsh-autosuggestions.zsh"
source "$PLUGIN_DIR/zsh-history-substring-search/zsh-history-substring-search.zsh"
source "$PLUGIN_DIR/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh"

# Bindings: history-substring-search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

bindkey -M emacs '^P' history-substring-search-up
bindkey -M emacs '^N' history-substring-search-down

eval "$(atuin init zsh --disable-up-arrow)"
