#!/usr/bin/env bash

export EDITOR="nvim"
export PAGER="less"
export VISUAL="nvim"
export READER="zathura"
export BROWSER="zen-beta"

export HISTFILE="$XDG_DATA_HOME/.zsh_history"
export HISTORY_IGNORE="(ls( *)?|cd( *)?|curl( *)?|rm|cp|pwd|exit|history)"
export HISTFILESIZE=10000
export HISTSIZE=10000
export SAVEHIST=10000
setopt APPENDHISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS
setopt SHARE_HISTORY
setopt autocd

# Disable Ctrl+S / Ctrl+Q
stty -ixon
