#!/usr/bin/env bash

setopt PROMPT_SUBST

autoload -Uz vcs_info

precmd() {
    vcs_info
}

declare -A fg=(
    [xgm_cyan]="#56B6C2"
    [xgm_green]="#98C379"
    [xgm_fg]="#ABB2BF"
    [xgm_yellow]="#E5C07B"
    [xgm_red]="#E06C75"
)

formats="%b%m%u%c"
actionformats="${formats} %a"

zstyle ":vcs_info:git*" enable git
zstyle ":vcs_info:git*" formats           "$formats"
zstyle ":vcs_info:git*" actionformats     "$actionformats"
zstyle ":vcs_info:git*" stagedstr         " %F{${fg[xgm_yellow]}}●%f"
zstyle ":vcs_info:git*" unstagedstr       " %F{${fg[xgm_green]}}●%f"
zstyle ":vcs_info:git*+set-message:*"  hooks git-untracked
zstyle ":vcs_info:git*" check-for-changes true

+vi-git-untracked() {
    if [[ $(git rev-parse --is-inside-work-tree 2> /dev/null) == 'true' ]] && \
    git status --porcelain | grep --max-count=1 '^??' &> /dev/null; then
        hook_com[misc]+=" %F{${fg[xgm_cyan]}}●%f"
    fi
}

current_dir="%F{${fg[xgm_yellow]}}%~%f"
PROMPT=$'${current_dir} ${vcs_info_msg_0_}\n⇒ '

last_commnad_status="%(?..%F{${fg[xgm_red]}}●%f)"
current_time="%F{${fg[xgm_fg]}}%*%f"
RPROMPT="${last_commnad_status} ${current_time}"
