* ~/dotfiles

Este repositorio contiene los archivos de configuración de Linux. Eres
libre de ver, tomar y modificar lo que gustes, sin embargo, ten en
cuenta que lo que aquí se muestra son mis preferencias personales, por
tal razón te sugeriría que revises bien lo que tomes antes de adjuntarlo
a tú configuración.

** Distro: Arch Linux
Uso [[https://archlinux.org/][Arch Linux]] como única distro principal. Me gusta la simpleza de la
distro; me gusta la riqueza de paquetes de [[https://archlinux.org/packages/][Pacman]] y [[https://aur.archlinux.org/][AUR]]; me gusta la
buena y completa documentación que tiene consigo.
** Window Manager: Openbox
[[http://openbox.org][Openbox]] es un, y mi actual, /floating/ window manager. Es una excelente
opción a un desktop environment ya que trae lo justo para funcionar y no
adiciona ningún tipo blodware que nadie pidió.

[[https://i3wm.org/][I3wm]] es, cunado tengo ganas, el /tiling/ window manager que
uso. suficiente para mi, cumple con mis necesidades. Es fácil de
configurar y fácil de usar, sin embargo, quizá un poco limitado en
cuanto a que tanto puedes hacer con el.

Mi configuración la puedes encontrar aquí: [[file:.config/i3/][i3wm]], [[file:.config/openbox/][Openbox]]

** Status Bars: Poylbar
[[https://polybar.github.io/][Polybar]], una status bar sencilla, fácil de usar, fácil de configurar. No
es especial en nada pero cumple.

En este caso los créditos de la configuración no me pertenecen, utilizo
un tema hecho por un usuario llamado [[https://github.com/adi1090x][adi1090x]] llamado [[https://github.com/adi1090x/polybar-themes#blocks][blocks]] con mis
respectivos retoques.

** Window Switcher: Rofi
Mi window swicher de preferencia, más por lo estético, dmenu me parece
muy /plano/. Pero igualmente ligero, rápido y simple, que es lo que se
busca.

Los créditos del la configuración también le pertenecen a [[https://github.com/adi1090x][adi1090x]] con
su tema llamado [[https://github.com/adi1090x/polybar-themes#blocks][blocks]]. Mi configuración es exactamente la que el
propone.

** Emulador de Terminal: St
En mi búsqueda de la simpleza, he utilizado muchos emuladores de
terminal pero solo con dos he encontrado lo que busco: [[https://st.suckless.org/][st]] y antiguamente
[[https://alacritty.org/][Alacritty]]

Mi configuración la puedes encontrar aquí: [[file:.config/alacritty/alacritty.yml][Alactritty]], [[#][st]].
*** Terminal Multiplexer: Tmux
Un paquete fundamental ya que [[https://st.suckless.org/][st]] no cuenta ni con paneles ni pestañas.
Tmux te permite tener múltiples sesiones de terminal en una misma
ventana, con el menor esfuerzo posible.

Mi configuración, como siempre, la puedes encontrar aquí: [[file:.tmux.conf][Tmux]].
** File Manager - Ranger
Ranger es mi file manager para todo, excepto para esos casos en lo que
me toca arrastrar un archivo al browser. Es simple, es rápido, utiliza
los atajos de teclado de Vim, es muy extensible (está escrito en
Python).

Mi configuración la puedes encontrar aquí: [[file:.config/ranger][Ranger]].
** Editor de Texto - NeoVim/Emacs
Uso [[https://neovim.io/][Neovim]] para programar, [[https://www.gnu.org/software/emacs/][Emacs]] para el resto de tareas que involucran
archivos de texto. Aunque a veces me siento tentando al pecado y utilizo
Emacs para programar.

Mi configuración: [[file:.config/nvim/][Nvim]] y [[file:.emacs.d/][Emacs]].
** Otro
Paquetes no listados:

- Browser: [[https://www.mozilla.org/en-US/firefox/][Firefox]]
- Document viewer: [[https://wiki.archlinux.org/title/Zathura][Zathura]]
- Media Player: [[https://wiki.archlinux.org/title/Mpv][Mpv]]
- Music Player: [[https://wiki.archlinux.org/title/Music_Player_Daemon][Mpd]] + Mpc + [[https://github.com/xgabrielmorales/rofi-mpd][Rofi MPD]] (Mi propio script)

*** Fuentes tipográficas
- Iconos: [[https://github.com/AT-UI/feather-font][Feather]]
- Monoespaciada: [[https://www.jetbrains.com/lp/mono/][JetBrains Mono Nerd Font]]
- Proporcional: [[https://developer.apple.com/fonts/][SF Pro]]
