map alt+shift+v paste_from_clipboard
map alt+shift+c copy_to_clipboard

map alt+shift+home      change_font_size all 0
map alt+shift+page_up   change_font_size all +0.5
map alt+shift+page_down change_font_size all -0.5
