#!/bin/sh

# Directories
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

alias dl="cd ~/Downloads && ls -l"
alias doc="cd ~/Documents && ls -l"
alias dotfiles="cd ~/dotfiles && ls -l"
alias work="cd ~/Documents/Work && ls -la"
alias cdr='cd $(git rev-parse --show-toplevel)'

# Clipboard
alias cbcopy="xclip -selection clipboard"
alias cbpaste="xclip -selection clipboard -o"

# Shortcuts
alias ipv4="ip addr show | grep 'inet ' | grep -v '127.0.0.1' | awk '{printf \"%s: %s\n\", \$NF, \$2}'"
alias ls="exa -F --all --header --group-directories-first --icons"
alias vim="nvim"

# Development
alias k="kubectl"

# Functions
ext() {
    if [ ! -f "$1" ]; then
        echo "'$1' It is not a recognized file."; exit
    fi

    case "$1" in
        *.7z)      7z x       "$1" ;;
        *.Z)       uncompress "$1" ;;
        *.tar.bz2) tar xjf    "$1" ;;
        *.bz2)     bunzip2    "$1" ;;
        *.tar.gz)  tar xzf    "$1" ;;
        *.gz)      gunzip     "$1" ;;
        *.rar)     unrar e    "$1" ;;
        *.tar)     tar xf     "$1" ;;
        *.tar.xz)  tar Jxvf   "$1" ;;
        *.tbz2)    tar xjf    "$1" ;;
        *.tgz)     tar xzf    "$1" ;;
        *.zip)     unzip      "$1" ;;
    esac
}
