#!/bin/sh

export EDITOR="nvim"
export PAGER="less"
export VISUAL="nvim"
export READER="zathura"
export BROWSER="zen-browser"

export HISTFILE="$XDG_DATA_HOME/.zsh_history"
export HISTORY_IGNORE="(ls|ls *|cd|pwd|exit|history|cd -|cd ..|rm|curl|curl *)"
export HISTFILESIZE=10000
export HISTSIZE=10000
export SAVEHIST=10000
setopt APPENDHISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS
setopt SHARE_HISTORY

# See: https://wiki.archlinux.org/title/GNOME/Keyring#SSH_keys
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/gcr/ssh"

# Disable Ctrl+S / Ctrl+Q
stty -ixon
