#!/bin/sh

export EDITOR="nvim"
export VISUAL="nvim"
export READER="zathura"
export BROWSER="librewolf"

export HISTFILE="$XDG_DATA_HOME/.zsh_history"
export HISTORY_IGNORE="(ls|cd|pwd|exit|history|cd -|cd ..|rm)"
export HISTFILESIZE=10000
export HISTSIZE=10000
export SAVEHIST=10000
setopt APPENDHISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt SHARE_HISTORY

# See: https://bitwarden.com/help/ssh-agent/#configure-bitwarden-ssh-agent
export SSH_AUTH_SOCK="$HOME/.bitwarden-ssh-agent.sock"

# Disable Ctrl+S / Ctrl+Q
stty -ixon
