arch = [
    "blueman",
    "bluez",
    "bluez-utils",
    "libpulse",
    "pavucontrol",
    "pipewire",
    "pipewire-alsa",
    "pipewire-jack",
    "pipewire-pulse",
    "playerctl",
    "vlc",
    "wireplumber",
]
