arch = [
    "cursor-bin",
    "diff-so-fancy",
    "docker",
    "docker-buildx",
    "docker-compose",
    "git",
    "git-extras-git",
    "npm",
    "openresolv",
    "postgresql-libs",
    "postman-agent",
    "python-pip",
    "python-pipx",
    "wireguard-tools",
]

flatpak = [
    "com.jetbrains.DataGrip",
]

pipx = [
    "poetry",
    "uv",
]
