arch = [
    "ansible",
    "ctop",
    "docker",
    "docker-compose",
    "git",
    "git-extras-git",
    "npm",
    "postgresql-client",
    "postman-agent",
    "python-pip",
    "python-pipx",
    "visual-studio-code-bin",
]

pipx = [
    "poetry",
    "uv",
]
