arch = [
    "diff-so-fancy",
    "docker",
    "docker-buildx",
    "docker-compose",
    "fd",
    "git",
    "git-extras-git",
    "github-cli",
    "hunspell",
    "luarocks",
    "neovim",
    "npm",
    "openresolv",
    "postgresql-libs",
    "postman-agent",
    "python-pip",
    "python-pipx",
    "ripgrep",
    "wireguard-tools",
]

flatpak = [
    "com.jetbrains.DataGrip",
]

pipx = [
    "commitizen",
    "poetry",
    "uv",
]
