arch = [
    "openbox",
    "picom",
    "rofi",
    "rofi-calc",
    "rofi-emoji",
    "tint2",
    "xdotool",
    "xfce4-notifyd",
    "xorg-server",
    "xorg-xev",
    "xorg-xinit",
    "xorg-xrandr",
    "xorg-xset",
]
