arch = [
    "7zip",
    "bind",
    "flatpak",
    "gnome-keyring",
    "less",
    "man-db",
    "man-pages",
    "openssh",
    "pacman-contrib",
    "rsync",
    "sshfs",
    "stow",
    "ufw",
    "unrar",
    "unzip",
    "usbutils",
    "vim",
    "wget",
    "wmctrl",
    "xclip",
    "xdg-user-dirs",
    "xfce-polkit",
    "zip",
]

flatpak = [
    "com.github.tchx84.Flatseal",
]
