#!/bin/bash
output=$(pactl list sinks | awk '{if(/Active Port:/) print $3}' | cut -d "-" -f 3)

toggle_audio_output() {
	output=$(pactl list sinks | awk '{if(/Active Port:/) print $3}' | cut -d "-" -f 3)
	if [ "$output" = "headphones" ]; then
		pactl set-default-sink alsa_output.pci-0000_0a_00.6.analog-stereo
	elif [ "$output" = "lineout" ]; then
		pactl set-default-sink alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1
	fi
}

audio_output_status() {
	if [ "$output" = "headphones" ]; then
		echo ""
	elif [ "$output" = "lineout" ]; then
		echo ""
	fi
}

case $1 in
	"--status")
			audio_output_status
		;;
	"--toggle")
			toggle_audio_output
		;;
esac
