#!/usr/bin/env bash

mic_status() {
	status=$(pactl get-source-mute @DEFAULT_SOURCE@ | grep -o "Mute: yes")
	volume=$(pactl get-source-volume @DEFAULT_SOURCE@ | awk '{print $5}')
	[[ $status == "Mute: yes" ]] && echo  || echo " $volume";
}

case $1 in
	"--status")
			mic_status
		;;
	"--toogle")
			pactl set-source-mute @DEFAULT_SOURCE@ toggle
			polybar-msg action "#microphone.hook.0"
		;;
	"--inc")
			pactl set-source-volume @DEFAULT_SOURCE@ +5%
			polybar-msg action "#microphone.hook.0"
		;;
	"--dec")
			pactl set-source-volume @DEFAULT_SOURCE@ -5%
			polybar-msg action "#microphone.hook.0"
		;;
esac
