#!/bin/bash

POLYBAR_PATH="$HOME/.config/polybar/modules.ini"
output=$(pactl list sinks | awk '{if(/Active Port:/) print $3}' | cut -d "-" -f 3)

if [ "$output" = "headphones" ]; then
	pactl set-sink-port @DEFAULT_SINK@ analog-output-lineout
	sed --in-place --expression 's/ramp-volume-0\ =\ /ramp-volume-0 = /' $POLYBAR_PATH
	polybar-msg cmd restart
elif [ "$output" = "lineout" ]; then
	pactl set-sink-port @DEFAULT_SINK@ analog-output-headphones
	sed --in-place --expression 's/ramp-volume-0\ =\ /ramp-volume-0 = /' $POLYBAR_PATH
	polybar-msg cmd restart
fi
