[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.08"

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
dynamic_title = false
startup_mode = "Maximized"
title = "Alacritty"

[window.dimensions]
columns = 180
lines = 40

[window.padding]
x = 8
y = 9

[general]
import = [
    "~/.config/alacritty/fonts.toml",
    "~/.config/alacritty/colors.toml",
    "~/.config/alacritty/bindings.toml",
]
