* Configuración de Neovim
** Indentación
Por defecto, en mi configuración, se usan tabs para indentar, sin
embargo, hay casos especiales en los que se redefine la indentación de
acuerdo al tipo de archivo que se esté usando.

*** Indentación con Tabs
La siguiente configuración se define para el uso de tabs como método de
indentación:

#+BEGIN_SRC
  set noexpandtab
  set tabstop=4
  set shiftwidth=4
  set softtabstop=0
#+END_SRC

=noexpandtab=, usa tabs en lugar de espacios para indentar.

=tabstop=, establece la el ancho de un carácter de tab.

=shiftwidth=, establece la cantidad de columnas (espacios) a insertar o
borrar cuando se utilicen los comandos de indentación.

=softtabstop=, define la cantidad de columnas (espacios) a insertar
cuando se utiliza la tecla <Tab> y a borrar cuando se utiliza la tecla
<BS> (backspace), si su valor es 0, entonces insertará o borrará un
carácter de tab.

*NOTA:* No confundir la tecla <Tab> con el carácter tab ya que
dependiendo de la configuración, la tecla <Tab> *dará como resultado o
no* un carácter de tab.

*** Indentación con Espacios
Si se quiere redefinir la indentación para usar espacios de acuerdo al
tipo de archivo lo podrás hacer de la siguiente manera:

#+BEGIN_SRC
  autocmd FileType python setlocal expandtab softtabstop=4
#+END_SRC

La línea anterior redefine la indentación para los archivos de python
=(*.py)=. Con la instrucción =expandtab= se especifica que se deben
usar espacios en lugar de tabs, y con la instrucción =softtabstop=4=
definimos el comportamiento de la tecla <Tab> y <BS> (backspace) la
cual al dicta que al presionar un la tecla <Tab> se insertarán 4
espacios y al presionar la tecla <BS> se borrarán 4 espacios.
