#!/usr/bin/bash

killall -q -9 polybar picom plank xfce-polkit

# Restore Wallpaper
/usr/bin/nitrogen --restore &

# Status bar (Polybar)
/usr/bin/tint2 &

# Task Switcher
/usr/bin/skippy-xd --start-daemon &

# Notification daemon
/usr/lib/xfce4/notifyd/xfce4-notifyd &

# Key repeat delay
/usr/bin/xset r rate 200 30 &

# Polkit
/usr/lib/xfce-polkit/xfce-polkit &

sleep 3;

# Redshift
redshift &
