#!/usr/bin/env bash

killall -q -9 polybar picom plank xfce-polkit

# Restore Wallpaper
/usr/bin/env nitrogen --restore &

# Status bar (Polybar)
/usr/bin/env tint2 &

# Task Switcher
/usr/bin/env skippy-xd --start-daemon &

# Key repeat delay
/usr/bin/env xset r rate 200 30 &

# Notification daemon
/usr/lib/xfce4/notifyd/xfce4-notifyd &

# Key repeat delay
/usr/bin/xset r rate 200 30 &

# Polkit
/usr/lib/xfce-polkit/xfce-polkit &

sleep 3;

# Redshift
/usr/bin/env redshift &
